@startuml win_load_css

partition "Win::load_css()"{  
  start
  :Create CssProvider;
  :CssProvider|
  if (Get path to style sheet) then (success)
    if (Load style sheet?) then (success)
      :Apply style from provider;
    else (failure)
      :Emit warning;
    endif
  else (failure)
  endif
  stop
}
@enduml