@startuml win_make_suggestion_buttons
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/grelltrier/RedDress-PlantUML/master/style.puml

partition "Win::make_suggestion_buttons()"{  
  start
  :Make storage for buttons;
  :<<CentralBuffer>>
      ButtonStorage]
  :Make a vector of labels
  for the suggestion buttons;
  
  while (for button label) is (next)
    :Make a Button
    Set its style class
    Set its label;

    :Connect the buttons 'clicked' 
    event to sending a
    SubmitText message;

    :Add the button to ButtonStorage;
  endwhile (end)

  :<<CentralBuffer>>
      ButtonStorage]
  stop
}
@enduml