name: "Install_deps"
description: "Installs the dependencies, checks out the code and sets up caching"

runs:
  using: "composite"
  steps:
    - name: Update repos
      shell: bash
      run: sudo apt-get update
    - name: Upgrade system
      shell: bash
      run: sudo apt-get upgrade -y
    - name: Install GTK3
      shell: bash
      run: sudo apt-get install -q -y binutils libgtk-3-dev libwayland-dev libgtk-layer-shell-dev
