@startuml decoder
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/grelltrier/RedDress-PlantUML/master/style.puml

package decoder {

    +class Decoder {
        receiver: mpsc::Receiver<(String, String)>
        text_left_of_cursor: String
        text_right_of_cursor: String
        prev_submissions: Vec<Submission>

        {static} +new(ui_connection: UIConnector, receiver: mpsc::Receiver<(String, String)>)
        +decode_text(text_to_decode: String): Vec<Submission>
        +decode_gesture(_x: i32, _y: i32)
        +get_gesture_result(_x: i32, _y: i32): String
        update_surrounding_text()
    }

    Decoder *-- keyboard.UIConnector : > uses to send messages to the UI
    Decoder -- submitter.Submission : > receives to decode
}
@enduml