@startuml
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/grelltrier/RedDress-PlantUML/master/style.puml

Messages - [UI]
[UI] --> Input
Input -- [Keyboard]
Decode -- [Decoder]
Submit -- [Submitter]
[Keyboard] --> Decode
[Keyboard] --> Submit
Decoder --> Messages
Keyboard --> Messages
Submitter --> Messages

@enduml