@startuml grid_builder_make_stack

partition "GridBuilder::make_stack(relm, layout_meta_hashmap)"{  
  start
  :Make new stack;
  :stack = Stack]
  :Make new storage for key references;
  :    <<CentralBuffer>>
  KeyReferences storage]

  while (for each LayoutMeta in layout_meta_hashmap) is (true)
    while (for each view in LayoutMeta) is (true)
      :grid_name = GridBuilder::make_grid_name();
      :(grid, key_refs) = GridBuilder::make_grid();
      :Add grid to stack;
      while (for key in key_refs) is (true)
        :grid_name = GridBuilder::make_grid_name();
        :(grid, key_refs) = GridBuilder::make_grid();
        :Add grid to stack;
        :Add key_refs from new grid to KeyReferences storage;
      endwhile (false)
    endwhile (false)
  endwhile (false)
  :Shrink hashmap_with_key_refs;
  :(stack, hashmap_with_key_refs)]

  stop
}
@enduml