@startuml win_make_suggestion_buttons

partition "Win::make_suggestion_buttons()"{  
  start
  :Make storage for buttons;
  :<<CentralBuffer>>
      ButtonStorage]
  :Make a vector of labels
  for the suggestion buttons;
  
  while (Processed all button labels?) is (no)
    :Make a Button
    Set its style class
    Set its label;

    :Connect the buttons 'clicked' 
    event to sending a
    SubmitText message;

    :Add the button to storage;
  endwhile (yes)

  :<<CentralBuffer>>
      ButtonStorage]
  stop
}
@enduml