@startuml keyboard_input

partition "keyboard_input"{

  start
  if (check interaction) then (tap)
    if(short press?) then (yes)
      :Get closest key to interaction;
      :key = closest_key]
      :Remember layout/view of last active key
      Remember last active key;
    else (no)
      :key = last active key]
    endif
    if (Check key) then (is some)
      :Execute the keys actions for the input interaction;
    else (is none)
    endif
  else (swipe)
    if (Begin?) then (yes)
      :Tell UI to release all
      latched keys and
      the last active key;
      :Tell submitter to release
      all keys and modifiers;
    elseif (Update?) then (yes)
      :Notify the interpreter
      about the new point
      of the gesture;
    else (Finish)
      :Get most likely word for
      gesture from interpreter;
      :Submit the word;
    endif
  endif
  stop
}
@enduml