@startuml layout_deserialized_from
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/grelltrier/RedDress-PlantUML/master/style.puml

partition "LayoutDeserialized::from()"{
    start

    if (Deserialize from) then (file)
        :Get file name;
        if (file name = 'previous') then (no)
        else (yes)
            :Err()]
            stop
        endif
        :file_name]
        :Open file;
        :yaml_file]
        :serde_yaml::from_reader(yaml_file);
        :result]
    else (fallback_string)
        :serde_yaml::from_str(fallback_string);
        :result]
    endif

    if (result) then (success)
        :deserialized_layout]
        :Ok(file_name, deserialized_layout)]
        note left
           The layout needs
           default information
           added before it 
           can be used to 
           construct a
           Keyboard from it.
           This is why it later
           gets converted 
           to a LayoutMeta 
        end note
        stop
    else (error)
        :Emit info;
        :Err()]
        stop
    endif
}

@enduml