@startuml layout_meta_from
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/grelltrier/RedDress-PlantUML/master/style.puml

partition "LayoutMeta::from()"{
  
  start
  :LayoutYamlParser::get_layouts();
  :         <<CentralBuffer>>
  LayoutDeserialized storage]

  :Create LayoutMeta storage;
  : <<CentralBuffer>>
  LayoutMeta storage]
  while (more LayoutDeserialized?) is (yes)
    :LayoutMeta::from(layout_deserialized);
    :result]
    if (result) then (Ok)
    :LayoutMeta]
    :Add to storage;
    else (no)
        :Emit error;
    endif
  endwhile (no)

  :         <<CentralBuffer>>
  LayoutDeserialized storage]

  stop
}
@enduml