@startuml reduced_keyboard_execute_tap_actions
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/grelltrier/RedDress-PlantUML/master/style.puml
!pragma useVerticalIf on

partition "keyboard_execute_tap_actions"{

  start
  :If the last switch was temporary,
  switch back to previous layout;
  
  if () then (actions)
    while (for action to execute) is (next)
      if (FeedbackPressRelease?) then (yes)
        if (press?) then (yes)
          :Tell UI to display the press of the button;
        elseif (key in latched_keys?) then (yes)
        else (no)
          :Tell UI to display the release of the button;
        endif
      elseif (EnterString?) then (yes)
        :Send text of the button to the decoder;
        :Vector of submissions]
        :Submit all of the returned submissions;
      endif
    endwhile (end)
  else (no actions)
  endif
  stop
}
@enduml