name: examples

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - "1.63.0"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install_deps
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo check --all --examples

  examples_all_features:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
         # - stable
          - nightly
         # - "1.63.0"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install_deps
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo check --all --examples --all-features
