name: test

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
        #  - stable
          - nightly
        #  - "1.63.0"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install_deps
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Test
        run: cargo test

  test_all_features:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
        #  - stable
          - nightly
        #  - "1.63.0"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install_deps
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Test
        run: cargo test --all-features
